import type { AnalysisResult, FundamentalsAnalysisResult } from '@chartanalyzer/shared';

/**
 * Shape of the rows this feature reads back from Supabase.
 *
 * Kept local to the feature rather than in `packages/shared` on purpose: the
 * API writes these columns through the service-role client and has no matching
 * type today, so there is only one call site. Move it to shared the moment the
 * backend needs the same shape.
 *
 * The one thing that IS shared is `analysis_result`: the API validates every
 * model response into `AnalysisResult` before storing it, and this renders it
 * back, so a divergence between the two must be a compile error rather than a
 * blank section on the report.
 */
export interface AnalysisRow {
  id: string;
  status: 'queued' | 'processing' | 'complete' | 'failed';
  source_type: 'paste' | 'upload';
  /** Where the analysis came from. 'watchlist_daily' rows are generated by
   *  the briefing job, 'live' rows by the live chart view, and 'fundamentals'
   *  rows by the Fundamentals tab's Analyze with AI — none of them are
   *  uploaded by the user. */
  source: 'manual' | 'watchlist_daily' | 'live' | 'fundamentals';
  /** Storage path of the analyzed chart, inside the private `chart-images`
   *  bucket — an uploaded screenshot for `source: 'manual'`, the generated
   *  candlestick image for `source: 'watchlist_daily'` and `'live'`. Must be
   *  signed before
   *  it can be used as an image `src`. */
  image_key: string;
  symbol_raw: string | null;
  symbol: string | null;
  /** The catalogue instrument a generated analysis was run on; null for an upload. */
  instrument_id: string | null;
  /** Chart window a generated analysis was read from, in days; null for an upload. */
  analysis_lookback_days: number | null;
  /**
   * The structured read the current prompts produce — the whole report, in
   * one column. Null for rows analyzed before those prompts (which render
   * from the legacy columns below) and for rows that have not completed.
   */
  analysis_result: AnalysisResult | null;
  /** Promoted out of `analysis_result` so the History list need not parse it. */
  setup_format: 'confirmed' | 'conditional' | 'two_scenario' | 'none' | null;
  structure_state: 'uptrend' | 'downtrend' | 'range' | 'transition' | null;
  instrument_type: string | null;
  timeframe: string | null;
  /**
   * The structured fundamentals read — see FundamentalsAnalysisResult in
   * packages/shared. Null for every row except a completed
   * source='fundamentals' analysis.
   */
  fundamentals_result: FundamentalsAnalysisResult | null;
  /** Promoted out of `fundamentals_result` so the History list need not parse it. */
  fundamentals_stance: 'attractive' | 'not_attractive' | 'mixed' | null;
  /* --- legacy reading columns; only rows with a null analysis_result use them.
     Nothing writes these any more: the current prompts produce no sentiment,
     no pattern names, and levels as bands rather than prices. --------------- */
  asset_class: string | null;
  trend: string | null;
  volatility: string | null;
  volume_reading: string | null;
  sentiment: string | null;
  support_levels: number[] | null;
  resistance_levels: number[] | null;
  call_direction: string | null;
  call_confidence: number | null;
  call_entry: number | null;
  call_invalidation: number | null;
  call_target: number | null;
  horizon_candles: number | null;
  summary: string | null;
  /** When this analysis was emailed to its owner (daily briefing digest or
   *  Brief Now). Null means it was never emailed — which is every manual
   *  upload, every live run and every Analyze Now. */
  emailed_at: string | null;
  error_code: string | null;
  error_message: string | null;
  created_at: string;
}

export interface AnalysisPattern {
  id: string;
  analysis_id: string;
  pattern_key: string;
  confidence: number | null;
  pattern_note: string | null;
}
