/**
 * Shape of the rows this feature reads back from Supabase.
 *
 * Kept local to the feature rather than in `packages/shared` on purpose: the
 * API writes these columns through the service-role client and has no matching
 * type today, so there is only one call site. Move it to shared the moment the
 * backend needs the same shape.
 */
export interface AnalysisRow {
  id: string;
  status: 'queued' | 'processing' | 'complete' | 'failed';
  source_type: 'paste' | 'upload';
  /** Where the analysis came from. 'watchlist_daily' rows are generated by
   *  the briefing job and 'live' rows by the live chart view; neither is
   *  uploaded by the user. */
  source: 'manual' | 'watchlist_daily' | 'live';
  /** Storage path of the analyzed chart, inside the private `chart-images`
   *  bucket — an uploaded screenshot for `source: 'manual'`, the generated
   *  candlestick image for `source: 'watchlist_daily'` and `'live'`. Must be
   *  signed before
   *  it can be used as an image `src`. */
  image_key: string;
  symbol_raw: string | null;
  symbol: string | null;
  /** The catalogue instrument a generated analysis was run on; null for an upload. */
  instrument_id: string | null;
  /** Chart window a generated analysis was read from, in days; null for an upload. */
  analysis_lookback_days: number | null;
  asset_class: string | null;
  timeframe: string | null;
  trend: string | null;
  volatility: string | null;
  volume_reading: string | null;
  sentiment: string | null;
  support_levels: number[] | null;
  resistance_levels: number[] | null;
  call_direction: string | null;
  call_confidence: number | null;
  call_entry: number | null;
  call_invalidation: number | null;
  call_target: number | null;
  horizon_candles: number | null;
  summary: string | null;
  /** When this analysis was emailed to its owner (daily briefing digest or
   *  Brief Now). Null means it was never emailed — which is every manual
   *  upload, every live run and every Analyze Now. */
  emailed_at: string | null;
  error_code: string | null;
  error_message: string | null;
  created_at: string;
}

export interface AnalysisPattern {
  id: string;
  analysis_id: string;
  pattern_key: string;
  confidence: number | null;
  pattern_note: string | null;
}
